"""add Readers

Revision ID: 2408a9b40b6b
Revises: 960e8f17ccf2
Create Date: 2022-04-29 15:11:55.524010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2408a9b40b6b'
down_revision = '960e8f17ccf2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('readers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('books', sa.Column('pages', sa.Integer(), nullable=True))
    op.add_column('books', sa.Column('reader._id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_books_reader._id'), 'books', ['reader._id'], unique=False)
    op.create_foreign_key(None, 'books', 'readers', ['reader._id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'books', type_='foreignkey')
    op.drop_index(op.f('ix_books_reader._id'), table_name='books')
    op.drop_column('books', 'reader._id')
    op.drop_column('books', 'pages')
    op.drop_table('readers')
    # ### end Alembic commands ###
