"""Readers fix

Revision ID: e559995f1501
Revises: 2408a9b40b6b
Create Date: 2022-04-29 15:21:13.234293

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e559995f1501'
down_revision = '2408a9b40b6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('reader_id', sa.Integer(), nullable=False))
    op.drop_index('ix_books_reader._id', table_name='books')
    op.create_index(op.f('ix_books_reader_id'), 'books', ['reader_id'], unique=False)
    op.drop_constraint('books_reader._id_fkey', 'books', type_='foreignkey')
    op.create_foreign_key(None, 'books', 'readers', ['reader_id'], ['id'])
    op.drop_column('books', 'reader._id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('reader._id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'books', type_='foreignkey')
    op.create_foreign_key('books_reader._id_fkey', 'books', 'readers', ['reader._id'], ['id'])
    op.drop_index(op.f('ix_books_reader_id'), table_name='books')
    op.create_index('ix_books_reader._id', 'books', ['reader._id'], unique=False)
    op.drop_column('books', 'reader_id')
    # ### end Alembic commands ###
